//
// File generated by rootcint at Wed Apr  6 13:59:46 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EnergyTest_ETestPackageDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EnergyTest_ETestPackageDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::ETest ETest;
      #else
      class ETest  {
         public:
         //friend XX;
         int N; //
         int Low; //
         int High; //
         double phiD; //
         double phiMC; //
         double phiDMC; //
         double step; //
         double stepsq; //
         double d000; //
         double nD; //
         double nMC; //
         double D[50][50][50]; //
         double MC[50][50][50]; //
         double psi[50][50][50]; //
         double Dpart; //
         double MCpart; //
         double DMCpart; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ETest_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void ETest_Dictionary();
   static void delete_ETest(void *p);
   static void deleteArray_ETest(void *p);
   static void destruct_ETest(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ETest*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::ETest) == sizeof(::ROOT::Shadow::ETest));
      ::ETest *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::ETest),0);
      static ::ROOT::TGenericClassInfo 
         instance("ETest", "./ETest.h", 34,
                  typeid(::ETest), DefineBehavior(ptr, ptr),
                  &ETest_ShowMembers, &ETest_Dictionary, isa_proxy, 4,
                  sizeof(::ETest) );
      instance.SetDelete(&delete_ETest);
      instance.SetDeleteArray(&deleteArray_ETest);
      instance.SetDestructor(&destruct_ETest);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ETest*)
   {
      return GenerateInitInstanceLocal((::ETest*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ETest*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void ETest_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::ETest*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void ETest_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class ETest.
      typedef ::ROOT::Shadow::ETest ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::ETest*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "N", &sobj->N);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Low", &sobj->Low);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "High", &sobj->High);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "phiD", &sobj->phiD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "phiMC", &sobj->phiMC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "phiDMC", &sobj->phiDMC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "step", &sobj->step);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "stepsq", &sobj->stepsq);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d000", &sobj->d000);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nD", &sobj->nD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nMC", &sobj->nMC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "D[50][50][50]", sobj->D);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MC[50][50][50]", sobj->MC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "psi[50][50][50]", sobj->psi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Dpart", &sobj->Dpart);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MCpart", &sobj->MCpart);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DMCpart", &sobj->DMCpart);
   }

}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_ETest(void *p) {
      delete ((::ETest*)p);
   }
   static void deleteArray_ETest(void *p) {
      delete [] ((::ETest*)p);
   }
   static void destruct_ETest(void *p) {
      typedef ::ETest current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::ETest

/********************************************************
* EnergyTest_ETestPackageDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEnergyTest_ETestPackageDict();

extern "C" void G__set_cpp_environmentEnergyTest_ETestPackageDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ETest.h");
  G__cpp_reset_tagtableEnergyTest_ETestPackageDict();
}
#include <new>
extern "C" int G__cpp_dllrevEnergyTest_ETestPackageDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ETest */
static int G__EnergyTest_ETestPackageDict_818_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ETest* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ETest((const int) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) ETest((const int) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ETest((const int) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) ETest((const int) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_ETest));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EnergyTest_ETestPackageDict_818_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ETest*) G__getstructoffset())->Histo3DETest((TH3*) G__int(libp->para[0]), (TH3*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EnergyTest_ETestPackageDict_818_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ETest*) G__getstructoffset())->SetD((TH3*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EnergyTest_ETestPackageDict_818_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ETest*) G__getstructoffset())->ETestKnowingD((TH3*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EnergyTest_ETestPackageDict_818_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ETest* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ETest(*(ETest*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_ETest));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ETest G__TETest;
static int G__EnergyTest_ETestPackageDict_818_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ETest*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ETest*) (soff+(sizeof(ETest)*i)))->~G__TETest();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ETest*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ETest*) (soff))->~G__TETest();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EnergyTest_ETestPackageDict_818_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ETest* dest = (ETest*) G__getstructoffset();
   *dest = *(ETest*) libp->para[0].ref;
   const ETest& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ETest */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEnergyTest_ETestPackageDict {
 public:
  G__Sizep2memfuncEnergyTest_ETestPackageDict(): p(&G__Sizep2memfuncEnergyTest_ETestPackageDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEnergyTest_ETestPackageDict::*p)();
};

size_t G__get_sizep2memfuncEnergyTest_ETestPackageDict()
{
  G__Sizep2memfuncEnergyTest_ETestPackageDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEnergyTest_ETestPackageDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEnergyTest_ETestPackageDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ETest */
static void G__setup_memvarETest(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_ETest));
   { ETest *p; p=(ETest*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->N)-(long)(p)),105,0,0,-1,-1,-1,1,"N=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Low)-(long)(p)),105,0,0,-1,-1,-1,1,"Low=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->High)-(long)(p)),105,0,0,-1,-1,-1,1,"High=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->phiD)-(long)(p)),100,0,0,-1,-1,-1,1,"phiD=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->phiMC)-(long)(p)),100,0,0,-1,-1,-1,1,"phiMC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->phiDMC)-(long)(p)),100,0,0,-1,-1,-1,1,"phiDMC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->step)-(long)(p)),100,0,0,-1,-1,-1,1,"step=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->stepsq)-(long)(p)),100,0,0,-1,-1,-1,1,"stepsq=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->d000)-(long)(p)),100,0,0,-1,-1,-1,1,"d000=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nD)-(long)(p)),100,0,0,-1,-1,-1,1,"nD=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nMC)-(long)(p)),100,0,0,-1,-1,-1,1,"nMC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->D)-(long)(p)),100,0,0,-1,-1,-1,1,"D[50][50][50]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MC)-(long)(p)),100,0,0,-1,-1,-1,1,"MC[50][50][50]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->psi)-(long)(p)),100,0,0,-1,-1,-1,1,"psi[50][50][50]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Dpart)-(long)(p)),100,0,0,-1,-1,-1,1,"Dpart=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MCpart)-(long)(p)),100,0,0,-1,-1,-1,1,"MCpart=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->DMCpart)-(long)(p)),100,0,0,-1,-1,-1,1,"DMCpart=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEnergyTest_ETestPackageDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncETest(void) {
   /* ETest */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_ETest));
   G__memfunc_setup("ETest",485,G__EnergyTest_ETestPackageDict_818_0_1, 105, G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_ETest), -1, 0, 2, 1, 1, 0, 
"i - - 10 - - g - - 0 'false' flag_UNDERFLOW_OVERFLOW", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Histo3DETest",1123,G__EnergyTest_ETestPackageDict_818_0_2, 100, -1, -1, 0, 2, 1, 1, 0, 
"U 'TH3' - 10 - - U 'TH3' - 10 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetD",368,G__EnergyTest_ETestPackageDict_818_0_3, 100, -1, -1, 0, 1, 1, 1, 0, "U 'TH3' - 10 - hD", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ETestKnowingD",1286,G__EnergyTest_ETestPackageDict_818_0_4, 100, -1, -1, 0, 1, 1, 1, 0, "U 'TH3' - 10 - hMC", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("ETest", 485, G__EnergyTest_ETestPackageDict_818_0_5, (int) ('i'), G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_ETest), -1, 0, 1, 1, 1, 0, "u 'ETest' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ETest", 611, G__EnergyTest_ETestPackageDict_818_0_6, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EnergyTest_ETestPackageDict_818_0_7, (int) ('u'), G__get_linked_tagnum(&G__EnergyTest_ETestPackageDictLN_ETest), -1, 1, 1, 1, 1, 0, "u 'ETest' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEnergyTest_ETestPackageDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEnergyTest_ETestPackageDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEnergyTest_ETestPackageDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TH3 = { "TH3" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__EnergyTest_ETestPackageDictLN_ETest = { "ETest" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEnergyTest_ETestPackageDict() {
  G__EnergyTest_ETestPackageDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TH3.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__EnergyTest_ETestPackageDictLN_ETest.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEnergyTest_ETestPackageDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TH3);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_TMatrixTSparseDiaglEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EnergyTest_ETestPackageDictLN_ETest),sizeof(ETest),-1,295936,(char*)NULL,G__setup_memvarETest,G__setup_memfuncETest);
}
extern "C" void G__cpp_setupEnergyTest_ETestPackageDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEnergyTest_ETestPackageDict()");
  G__set_cpp_environmentEnergyTest_ETestPackageDict();
  G__cpp_setup_tagtableEnergyTest_ETestPackageDict();

  G__cpp_setup_inheritanceEnergyTest_ETestPackageDict();

  G__cpp_setup_typetableEnergyTest_ETestPackageDict();

  G__cpp_setup_memvarEnergyTest_ETestPackageDict();

  G__cpp_setup_memfuncEnergyTest_ETestPackageDict();
  G__cpp_setup_globalEnergyTest_ETestPackageDict();
  G__cpp_setup_funcEnergyTest_ETestPackageDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEnergyTest_ETestPackageDict();
  return;
}
class G__cpp_setup_initEnergyTest_ETestPackageDict {
  public:
    G__cpp_setup_initEnergyTest_ETestPackageDict() { G__add_setup_func("EnergyTest_ETestPackageDict",(G__incsetup)(&G__cpp_setupEnergyTest_ETestPackageDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEnergyTest_ETestPackageDict() { G__remove_setup_func("EnergyTest_ETestPackageDict"); }
};
G__cpp_setup_initEnergyTest_ETestPackageDict G__cpp_setup_initializerEnergyTest_ETestPackageDict;

