/********************************************************************
* EnergyTest_ETestPackageDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EnergyTest_ETestPackageDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEnergyTest_ETestPackageDict();
extern void G__cpp_setup_inheritanceEnergyTest_ETestPackageDict();
extern void G__cpp_setup_typetableEnergyTest_ETestPackageDict();
extern void G__cpp_setup_memvarEnergyTest_ETestPackageDict();
extern void G__cpp_setup_globalEnergyTest_ETestPackageDict();
extern void G__cpp_setup_memfuncEnergyTest_ETestPackageDict();
extern void G__cpp_setup_funcEnergyTest_ETestPackageDict();
extern void G__set_cpp_environmentEnergyTest_ETestPackageDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ETest.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TString;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TH1F;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TH3;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_TGraphErrors;
extern G__linked_taginfo G__EnergyTest_ETestPackageDictLN_ETest;

/* STUB derived class for protected member access */
